[tools]
rust = "latest"
python = "3.12"
uv = "latest"

[env]
PYO3_USE_ABI3_FORWARD_COMPATIBILITY = 1


[tasks."build:rust"]
description = "Build the Rust library and binaries"
run = "cargo build --no-default-features"

[tasks."test:rust"]
description = "Run all Rust unit tests"
run = "cargo test --no-default-features"

# Python tasks
[tasks."setup:py"]
description = "Set up the Python virtual environment using uv"
run = "uv venv && uv pip install maturin tiktoken datasets opencv-python"

[tasks."build:py"]
description = "Build and install the Python extension using uv and maturin"
run = "uv run --no-project maturin develop --release --features extension-module"

[tasks."test:py"]
description = "Run the Python verification script"
run = "uv run --no-project python verify.py"

# global tasks
[tasks.setup]
depends = ["setup:*"]

[tasks.build]
description = "Build neuronguard"
run = [
    { task = "build:rust" },
    { task = "build:py" },
]

[tasks.test]
depends = ["test:*"]

[tasks.docs]
description = "Build the pdoc HTML documentation"
run = "uv run pdoc -d google -o docs ./neuronguard"

[tasks."docs:view"]
description = "Open the generated documentation in your default browser"
depends = ["docs"]
run = "open docs/index.html"
