[tools]
python = "3.12"
uv = "latest"

[tasks."examples:getting_started_tabular:run"]
description = "Run the NeuronGuard Tabular Classification Getting Started Guide"
run = "uv run --no-project python main.py"
