[tools]
python = "3.12"
uv = "latest"

[tasks."examples:getting_started_batch:run"]
description = "Run the NeuronGuard Batch Processing Getting Started Guide"
run = "uv run --no-project python main.py"
